[versions]
agp = "9.4.1"
kotlin = "2.4.20"
composeUi = "1.12.1"
composeFoundation = "1.12.1"
composeMaterial3 = "1.4.0"
activityCompose = "1.13.0"
javaSourceTarget = "11"
jdkToolchain = "25"

[libraries]
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "composeUi" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "composeFoundation" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial3" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
